### ISSUE TITLE
basic auth broken

### ISSUE THREAD

**Issue by ajs124** [eclipse/thingweb.node-wot#290]
After upgrading from 0.7.0 to 0.7.1 (or master for that matter), http basic authentication does not work anymore.

A simple reproducer would be something like 
```javascript
Servient = require("@node-wot/core").Servient
HttpsClientFactory = require("@note-wot/binding-http").HttpsClientFactory
Helpers = require("@note-wot/core").Helpers
let servient = new Servient();
servient.addCredentials({
    "urn:test-thing": {
        "username": "admin",
        "password": "password"
    }
});
servient.addClientFactory(new HttpsClientFactory());

let wotHelper = new Helpers(servient);
wotHelper.fetch("https://some-thing").then(async (td) => {
    try {
        let w = await servient.start();
        let t = await w.consume(td);
        console.log(await t.readProperty("temperature"));
        process.exit(0);
    } catch (err) {
        console.error("Script error:", err);
        process.exit(1);
    }
}).catch((err) => { console.error("Fetch error:", err); });
```
The works on 0.7.0 but on later releases, it results in this:
```
HttpClient (readResource) sending GET to https://some-thing/properties/temperature                                              
Script error: Error: Client error: [object Promise]        
    at HttpClient.checkFetchResponse (/[…]/thingweb.node-wot/packages/binding-http/dist/http-client.js:349:19)
    at HttpClient.<anonymous> (/[…]/thingweb.node-wot/packages/binding-http/dist/http-client.js:98:30)
    at step (/[…]/thingweb.node-wot/packages/binding-http/dist/http-client.js:33:23)                                                
    at Object.next (/[…]/thingweb.node-wot/packages/binding-http/dist/http-client.js:14:53)                                         
    at fulfilled (/[…]/thingweb.node-wot/packages/binding-http/dist/http-client.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
on current master, the error reads like:
```
[binding-http] HttpClient (readResource) sending GET to https://some-thing/properties/temperature
Script error: Error: Client error: Unauthorized
    at HttpClient.checkFetchResponse (/[…]/thingweb.node-wot/packages/binding-http/dist/http-client.js:379:19)
    at HttpClient.<anonymous> (/[…]/thingweb.node-wot/packages/binding-http/dist/http-client.js:101:30)
    at step (/[…]/thingweb.node-wot/packages/binding-http/dist/http-client.js:33:23)
    at Object.next (/[…]/thingweb.node-wot/packages/binding-http/dist/http-client.js:14:53)
    at fulfilled (/[…]/thingweb.node-wot/packages/binding-http/dist/http-client.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
`git bisect run` names 86292ff7f55b63551a4b37118624531ea84ab2d4 as the first bad commit which was introduced in #201 by @relu91

**Comment by relu91** [comment]
Thanks for tracking down the bad commit and for providing an example. @danielpeintner could you please assign me to this issue? I'll check it ASAP.

**Comment by danielpeintner** [comment]
@ajs124 can you check https://github.com/eclipse/thingweb.node-wot/pull/292

**Comment by danielpeintner** [comment]
resolved by https://github.com/eclipse/thingweb.node-wot/pull/292

**Comment by erceguder** [comment]
Although supposed to be fixed, I am still having the same issue. Server running just fine btw -tried with Postman. Any ideas ? @danielpeintner @relu91

**Comment by relu91** [comment]
Are you exposing the Web Thing using node-wot? if it is not it might be that your server does not support basic authentication using the HTTP Headers. See #293 

Finally, are you sure that you are using the latest code of node-wot? I am not sure but the fix that I made may not be published yet.

**Comment by erceguder** [comment]
> Finally, are you sure that you are using the latest code of node-wot? I am not sure but the fix that I made may not be published yet.

Now I see the problem: fix is not published to npm yet. Thanks anyways.
